language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - githubUniversity@gmail.com
script:
- mvn clean verify --settings settings.xml
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify --settings settings.xml
- mvn sonar:sonar -Dsonar.organization=angelmart-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=1621953a44b24b9a2f9dfc82cef1ebdc17c9a23e
